api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from djgeojson.views import GeoJSONLayerView, TiledGeoJSONLayerView

from sights.models import Territory, Municipality, Place
from .views import placeasgeojson, PlaceAutocomplete, AllUserAutocomplete, ActiveUserAutocomplete, \
    MunicipalityAutocomplete, TerritoryAutocomplete, TaxaAutocomplete

urlpatterns = [
    # url(r'^place.geojson$',
    #     GeoJSONPlaceData.as_view(),
    #     name='geodata_place'),
    url(r'^municipality.geojson$', login_required(
        GeoJSONLayerView.as_view(model=Municipality, precision=3, simplify=0.5, properties=('name', 'code'))),
        name='geodata_municipality'),
    url(r'^territory.geojson$', login_required(
        GeoJSONLayerView.as_view(model=Territory, precision=3, simplify=0.5, properties=('name', 'code'))),
        name='geodata_territory'),
    url(r'^place.geojson$', placeasgeojson, name='geodata_place'),
    # url(r'^place/(?P<z>\d+)/(?P<x>\d+)/(?P<y>\d+).geojson$',
    #     TiledGeoJSONLayerView.as_view(model=Place), name='placetiled'),
    url(
        r'^active-user-autocomplete/$',
        ActiveUserAutocomplete.as_view(),
        name='active_user_autocomplete',
    ),
    url(
        r'^all-user-autocomplete/$',
        AllUserAutocomplete.as_view(),
        name='all_user_autocomplete',
    ),
    url(
        r'^taxa-autocomplete/$',
        TaxaAutocomplete.as_view(),
        name='taxa_autocomplete',
    ),
    url(
        r'^municipality-autocomplete/$',
        MunicipalityAutocomplete.as_view(),
        name='municipality_autocomplete',
    ),
    url(
        r'^territory-autocomplete/$',
        TerritoryAutocomplete.as_view(),
        name='territory_autocomplete',
    ),
    url(
        r'^place-autocomplete/$',
        PlaceAutocomplete.as_view(),
        name='place_autocomplete',
    ),
]

dbchiro/urls.py
from django.conf import settings
from django.conf.urls import url, include, static
from django.contrib.auth import views as auth_views
from django.contrib.auth.urls import views
from django.contrib.gis import admin

admin.autodiscover()
admin.site.index_title = 'Tables de données'
admin.site.site_header = 'Interface de gestion'

urlpatterns = [
                  url(r'^nested_admin/', include('nested_admin.urls')),
                  url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
                  url(r'^logout/$', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
                  url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
                  url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
                  url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
                  url(r'^reset/done/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
                  url(r'^admin/', admin.site.urls),
                  url(r'^admin/doc/', include('django.contrib.admindocs.urls'),
                      name='dbgestion_doc'),
                  url(r'', include('core.urls', namespace='core')),
                  url(r'^accounts/', include('accounts.urls', namespace='accounts')),
                  url(r'', include('blog.urls', namespace='blog')),
                  url(r'', include('sights.urls', namespace='sights')),
                  url(r'', include('management.urls', namespace='management')),
                  url(r'^synthesis/', include('synthesis.urls', namespace='synthesis')),
                  url(r'^api/', include('api.urls', namespace='api')),

              ] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

sights/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from sights.views import (PlaceUpdate, PlaceDelete, PlaceList, PlaceDetail, PlaceManagementCreate,
                          PlaceManagementUpdate, PlaceManagementDelete, BuildCreate, BuildUpdate, BuildDelete,
                          BridgeCreate, BridgeUpdate, BridgeDelete,
                          CaveCreate, CaveUpdate, CaveDelete, TreeCreate, TreeUpdate, TreeDelete, TreeDetail,
                          TreeGiteCreate,
                          TreeGiteUpdate, TreeGiteDelete,
                          SessionCreate, SessionDetail, SessionUpdate, SessionDelete, SessionMyList, SightingCreate,
                          SightingUpdate, SightingDelete, SightingDetail, SightingList,
                          SightingMyList, DeviceCreate, DeviceUpdate, DeviceDelete,
                          CountDetailCreate, CountDetailUpdate, CountDetailDelete,
                          PlaceCreate, PlaceMyList, SightingUserList, SessionChangePlaceUpdate)

urlpatterns = [
    # url de recherches de localités
    url(r'^place/search$', PlaceList.as_view(), name='place_search'),

    # User views relative URLS
    url(r'^user/place/list$',
        PlaceMyList.as_view(), name='place_mylist'),
    url(r'^user/session/list$',
        SessionMyList.as_view(), name='session_mylist'),
    url(r'^user/sighting/list$',
        SightingMyList.as_view(), name='sighting_mylist'),
    url(r'^user/(?P<pk>[0-9]+)/sighting/list',
        SightingUserList.as_view(), name='user_sighting_list'),

    # Place views
    url(r'^place/map$', login_required(TemplateView.as_view(
        template_name='sights/place_map.html')), name='place_map'),
    url(r'^place/tiledmap$', login_required(TemplateView.as_view(
        template_name='sights/place_map_tiled.html')), name='place_tiled_map'),
    url(r'^place/tilemap$', login_required(TemplateView.as_view(
        template_name='sights/place_tilemap.html')), name='place_tilemap', ),
    url(r'^place/add$', PlaceCreate.as_view(), name='place_create'),
    url(r'^place/(?P<pk>\d+)/detail$',
        PlaceDetail.as_view(), name='place_detail'),
    url(r'^place/(?P<pk>[0-9]+)/update$',
        PlaceUpdate.as_view(), name='place_update'),
    url(r'^place/(?P<pk>[0-9]+)/delete$',
        PlaceDelete.as_view(), name='place_delete'),

    # Place management relative URLS
    url(r'^place/(?P<pk>[0-9]+)/management/add$',
        PlaceManagementCreate.as_view(), name='management_create'),
    url(r'^management/(?P<pk>[0-9]+)/update$',
        PlaceManagementUpdate.as_view(), name='management_update'),
    url(r'^management/(?P<pk>[0-9]+)/delete$',
        PlaceManagementDelete.as_view(), name='management_delete'),

    # Build views
    url(r'^place/(?P<pk>[0-9]+)/build/add$',
        BuildCreate.as_view(), name='build_create'),
    url(r'^build/(?P<pk>[0-9]+)/update$',
        BuildUpdate.as_view(), name='build_update'),
    url(r'^build/(?P<pk>[0-9]+)/delete$',
        BuildDelete.as_view(), name='build_delete'),

    # Tree views
    url(r'^place/(?P<pk>[0-9]+)/tree/add$',
        TreeCreate.as_view(), name='tree_create'),
    url(r'^tree/(?P<pk>[0-9]+)/update$',
        TreeUpdate.as_view(), name='tree_update'),
    url(r'^tree/(?P<pk>[0-9]+)/delete$',
        TreeDelete.as_view(), name='tree_delete'),
    url(r'^tree/(?P<pk>[0-9]+)/detail$',
        TreeDetail.as_view(), name='tree_detail'),

    # TreeGite views
    url(r'^tree/(?P<pk>[0-9]+)/treegite/add$',
        TreeGiteCreate.as_view(), name='treegite_create'),
    url(r'^treegite/(?P<pk>[0-9]+)/update$',
        TreeGiteUpdate.as_view(), name='treegite_update'),
    url(r'^treegite/(?P<pk>[0-9]+)/delete$',
        TreeGiteDelete.as_view(), name='treegite_delete'),

    # Cave views
    url(r'^place/(?P<pk>[0-9]+)/cave/add$',
        CaveCreate.as_view(), name='cave_create'),
    url(r'^cave/(?P<pk>[0-9]+)/update$',
        CaveUpdate.as_view(), name='cave_update'),
    url(r'^cave/(?P<pk>[0-9]+)/delete$',
        CaveDelete.as_view(), name='cave_delete'),

    # Bridge views
    url(r'^place/(?P<pk>[0-9]+)/bridge/add$',
        BridgeCreate.as_view(), name='bridge_create'),
    url(r'^bridge/(?P<pk>[0-9]+)/update$',
        BridgeUpdate.as_view(), name='bridge_update'),
    url(r'^bridge/(?P<pk>[0-9]+)/delete$',
        BridgeDelete.as_view(), name='bridge_delete'),

    # Session relative URLS
    url(r'^place/(?P<pk>[0-9]+)/session/add$',
        SessionCreate.as_view(), name='session_create'),
    url(r'^session/(?P<pk>[0-9]+)/detail$',
        SessionDetail.as_view(), name='session_detail'),
    url(r'^session/(?P<pk>[0-9]+)/update$',
        SessionUpdate.as_view(), name='session_update'),
     url(r'^session/(?P<pk>[0-9]+)/change_place$',
         SessionChangePlaceUpdate.as_view(), name='sessionchangeplace_update'),
    url(r'^session/(?P<pk>[0-9]+)/delete$',
        SessionDelete.as_view(), name='session_delete'),

    # Device relative URLS
    url(r'^session/(?P<pk>[0-9]+)/device/add$',
        DeviceCreate.as_view(), name='device_create'),
    url(r'^device/(?P<pk>[0-9]+)/update$',
        DeviceUpdate.as_view(), name='device_update'),
    url(r'^device/(?P<pk>[0-9]+)/delete$',
        DeviceDelete.as_view(), name='device_delete'),

    # Sighting relative URLS
    url(r'^session/(?P<pk>[0-9]+)/sighting/add$',
        SightingCreate.as_view(), name='sighting_create'),
    url(r'^sighting/(?P<pk>[0-9]+)/detail$',
        SightingDetail.as_view(), name='sighting_detail'),
    url(r'^sighting/(?P<pk>[0-9]+)/update$',
        SightingUpdate.as_view(), name='sighting_update'),
    url(r'^sighting/(?P<pk>[0-9]+)/delete$',
        SightingDelete.as_view(), name='sighting_delete'),
    url(r'^sighting/list$',
        SightingList.as_view(), name='sighting_list'),

    # CountDetail relative URLS
    url(r'^sighting/(?P<pk>[0-9]+)/countdetail/add$',
        CountDetailCreate.as_view(), name='countdetail_create'),
    url(r'^countdetail/(?P<pk>[0-9]+)/update$',
        CountDetailUpdate.as_view(), name='countdetail_update'),
    url(r'^countdetail/(?P<pk>[0-9]+)/delete$',
        CountDetailDelete.as_view(), name='countdetail_delete'),
]

templates/sights/place_map.html
{% extends 'base_leaflet.html' %}
{% load leaflet_tags i18n %}
{% leaflet_js %}
{% leaflet_css %}
{% load geojson_tags %}
{% block content %}
    <h1><a href="{% url 'sights:place_create' %}" class="btn btn-primary pull-right"><i
            class="fa fa-fw fa-map-marker"></i>{% trans 'Créer une localité' %}</a>
        <i class="fa fa-fw fa-map"></i> Carte des localités</h1>
    <div id="progress">
        <div id="progress-bar"></div>
    </div>
    {% leaflet_map "main" %}
    <br/>
    <script type="text/javascript">
        var dataurl = '{% url "api:geodata_place" %}';
        window.addEventListener("map:init", function (event) {
            var markers = L.markerClusterGroup({chunkedLoading: true, spiderfyDistanceMultiplier: 3});

            var style_data = {
                radius: 8,
                fillColor: "#ff4c41",
                color: "#ddd",
                weight: 2,
                opacity: 1,
                fillOpacity: 0.8
            };


            var map = event.detail.map;

            map.spin(true);

            // Fonction plein écran
            map.addControl(new L.Control.Fullscreen());


            // Géolocalisation de l'utilisateur

            var locateOptions = {
                flyTo: true,
                title: 'Ma position',
                icon: 'fa fa-location-arrow',
            };

            L.control.locate(locateOptions).addTo(map);

            // Recherche par adresse
            map.addControl(new L.Control.Search({
                url: 'https://nominatim.openstreetmap.org/search?format=json&accept-language=de-DE&q={s}',
                jsonpParam: 'json_callback',
                propertyName: 'display_name',
                propertyLoc: ['lat', 'lon'],
                markerLocation: true,
                autoType: true,
                autoCollapse: true,
                minLength: 2,
                zoom: 13,
                text: 'Suchen...',
                textCancel: 'Annuler',
                textErr: 'Erreur'
            }));

            // Download GeoJSON data with Ajax
            fetch(dataurl, {
                credentials: "include"
            })
                .then(function (resp) {
                    return resp.json();
                })
                .then(function (data) {
                    var locationLayer = L.geoJson(data, {
                        onEachFeature: function onEachFeature(feature, layer) {
                            var props = feature.properties;
                            var content = `<a class="btn btn-primary btn-sm btn-block" align="center" style="color:white;" href="/place/${props.pk}/detail" target="_blank" style="font-color:white"><strong>${props.name}</strong></a>`;
                            layer.bindPopup(content);
                        }
                        ,
                        pointToLayer: function (feature, latlng) {
                            return L.circleMarker(latlng, style_data);
                        }
                    });
                    markers.addLayer(locationLayer).addTo(map);
                })
                .then(function () {
                    map.spin(false);
                });

        });
    </script>
{% endblock %}

templates/sights/place_map_tiled.html
{% extends 'base_leaflet.html' %}
{% load leaflet_tags %}
{% leaflet_js %}
{% leaflet_css %}
{% load geojson_tags %}
{% block content %}
    <h1><i class="fa fa-fw fa-map"></i> Carte des localités</h1>
    <div id="progress">
        <div id="progress-bar"></div>
    </div>
    {% leaflet_map "main" %}
    <br/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-tilelayer-geojson/1.0.4/TileLayer.GeoJSON.min.js"></script>
    <script type="text/javascript">
        {#var dataurl = '{% url "api:geodata_place" %}';#}
        window.addEventListener("map:init", function (event) {
            var style = {
                "clickable": true,
                "color": "#00D",
                "fillColor": "#00D",
                "weight": 1.0,
                "opacity": 0.3,
                "fillOpacity": 0.2
            };
            var hoverStyle = {
                "fillOpacity": 0.5
            };

            var geojsonURL = '/place/api/{z}/{x}/{y}.geojson';
            var geojsonTileLayer = new L.TileLayer.GeoJSON(geojsonURL, {
                    credentials: true,
                    clipTiles: true,
                    unique: function (feature) {
                        return feature.id;
                    }
                }, {
                    style: style,
                    onEachFeature: function (feature, layer) {
                        if (feature.properties) {
                            var popupString = '<div class="popup">';
                            for (var k in feature.properties) {
                                var v = feature.properties[k];
                                popupString += k + ': ' + v + '<br />';
                            }
                            popupString += '</div>';
                            layer.bindPopup(popupString);
                        }
                        if (!(layer instanceof L.Point)) {
                            layer.on('mouseover', function () {
                                layer.setStyle(hoverStyle);
                            });
                            layer.on('mouseout', function () {
                                layer.setStyle(style);
                            });
                        }
                    }
                }
            );
            var credentialGeojsonTileLayer = geojsonTileLayer.credentials;
            credentialGeojsonTileLayer.addTo(map);
            {#map.addLayer(geojsonTileLayer);#}
        });
    </script>
{% endblock %}

templates/sights/place_tilemap.html
{% extends 'base_leaflet.html' %}
{% load leaflet_tags %}
{% load geojson_tags %}
{% block content %}
    <h1><i class="fa fa-fw fa-map"></i> Carte des localités</h1>
    {% leaflet_map "main" %}
    <br/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-tilelayer-geojson/1.0.4/TileLayer.GeoJSON.min.js"></script>
    <script src="js/leaflet/leaflet.ajax.min.js"></script>
    <script type="text/javascript">
        function popUp(f, l) {
            var out = [];
            if (f.properties) {
                for (key in f.properties) {
                    out.push("<b>" + key + "</b>: " + f.properties[key]);
                }
                l.bindPopup(out.join("<br />"));
            }
        }

        var territory_style = {
            "color": "#1779ba",
            "weight": 2,
            "opacity": 0.5
        };
        var location_style = {
            "clickable": true,
            "color": "#00D",
            "fillColor": "#00D",
            "weight": 1.0,
            "opacity": 0.3,
            "fillOpacity": 0.2
        };
        var location_hoverstyle = {
            "fillOpacity": 0.5
        };
        var data_territory = new L.GeoJSON.AJAX(["{% url "data_territory" %}"], {
            onEachFeature: popUp,
            style: territory_style
        }).addTo(map);
        var geojsonTileLayer = new L.TileLayer.GeoJSON('{% url "data_place_tile" %}', {
                clipTiles: true,
                unique: function (feature) {
                    return feature.id;
                }
            }, {
                style: style,
                onEachFeature: function (feature, layer) {
                    if (feature.properties) {
                        var popupString = '<div class="popup">';
                        for (var k in feature.properties) {
                            var v = feature.properties[k];
                            popupString += k + ': ' + v + '<br />';
                        }
                        popupString += '</div>';
                        layer.bindPopup(popupString);
                    }
                    if (!(layer instanceof L.Point)) {
                        layer.on('mouseover', function () {
                            layer.setStyle(location_hoverstyle);
                        });
                        layer.on('mouseout', function () {
                            layer.setStyle(location_style);
                        });
                    }
                }
            }
        );
        map.addLayer(geojsonTileLayer);

    </script>
{% endblock %}

templates/sights/tree_detail.html
{% extends 'base_fullwidth_leaflet.html' %}
{% load render_table from django_tables2 %}
{% block content %}
    <h1><i class="{{ icon | safe }}"></i> {{ title | safe }}</h1>
    <p>
        <small>Observation créée par <b>{{ object.created_by }}</b> le <b>{{ object.timestamp_create }}</b>
            et mise à jour le <b>{{ object.timestamp_update }}</b></small>
    </p>
    <div class="row">
        <div class="large-6 medium-12 columns">
            <div class="accordion" data-accordion>
                <li class="accordion-item is-active" data-accordion-item>
                    <a class="accordion-title">Informations principales</a>
                    <div class="accordion-content" data-tab-content>
                        <div class="row">
                            <div class="large-12 columns">
                                <label>Date de contrôle</label>
                                <div class="small callout">{{ object.visit_date }}</div>
                            </div>
                        </div>
                        <div class="callout secondary">
                            <div class="callout">
                            <h3>Contexte</h3>
                                <div class="row">
                                    <div class="large-6 small-12 columns">
                                        <label>Contexte</label>
                                        <div class="small callout">{{ object.context }}</div>
                                    </div>
                                    <div class="large-6 small-12 columns">
                                        <label>Peuplement forestier</label>
                                        <div class="small callout">{{ object.forest_stands }}</div>
                                    </div>
                                    <div class="large-6 small-12 columns">
                                        <label>Circomstance de la découverte</label>
                                        <div class="small callout">{{ object.circumstance }}</div>
                                    </div>
                                    <div class="large-6 small-12 columns">
                                        <label>Situation dans le milieu (dans le bois, en lisière, etc.) </label>
                                        <div class="small callout">{{ object.situation }}</div>
                                    </div>
                                </div>
                            </div>
                             <div class="callout">
                                <h3>Caractéristiques de l'arbre</h3>
                                <div class="row">
                                    <div class="large-4 medium-12 columns">
                                        <label>Espèce d'arbre</label>
                                        <div class="small callout">{{ object.tree_specie }}</div>
                                    </div>
                                    <div class="large-4 medium-6 columns">
                                        <label>Etat de l'arbre</label>
                                        <div class="small callout">{{ object.health }}</div>
                                    </div>
                                    <div class="large-4 medium-6 columns">
                                        <label>Diamètre de l'arbre à 1.30m du sol (en cm)</label>
                                        <div class="small callout">{{ object.tree_diameter }}</div>
                                    </div>
                                    <div class="large-6 columns">
                                        <label>Arbre debout</label>
                                        <div class="small callout">{{ object.standing }}</div>
                                    </div>
                                    <div class="large-6 columns">
                                        <label>Arbre protégé</label>
                                        <div class="small callout">{{ object.protected }}</div>
                                    </div>
                                </div>
                            </div>
                             <div class="callout">
                                <h3>Occupation</h3>
                                <div class="row">
                                    <div class="medium-12 columns">
                                        <label>Espèces</label>
                                        <div class="small callout">
                                            {% if object.bat_specie %}
                                                <ul>
                                                {% for sp in object.bat_specie.all|dictsort:"sys_order" %}
                                                    <li> {{ sp.codesp }}{% if d.sp_true %}*{% endif %}</b> (
                                                        {{ sp.common_name_fr }})
                                                    </li>
                                                {% endfor %}
                                            {% else %}
                                                Aucune espèce
                                            {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                             <div class="callout">
                                <h3>Caractérisation des gîtes</h3>
                                <div class="row">
                                    <div class="large-4 medium-12 columns">
                                        <label>Types de gîte(s)</label>
                                        <div class="small callout">
                                            {% if object.gite_type %}
                                                <ul>
                                                {% for gt in object.gite_type.all %}
                                                    <li> {{ gt.descr }}</li>
                                                {% endfor %}
                                            {% else %}
                                                Aucune type indiqué
                                            {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="large-4 medium-6 columns">
                                        <label>Origines du/des gîte(s)</label>
                                        <div class="small callout">
                                            {% if object.gite_origin %}
                                                <ul>
                                                {% for go in object.gite_origin.all %}
                                                    <li> {{ go.descr }}</li>
                                                {% endfor %}
                                            {% else %}
                                                Aucune origine indiquée
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="large-4 medium-6 columns">
                                        <label>Emplacement du/des gîte(s)</label>
                                        <div class="small callout">
                                            {% if object.gite_localisation %}
                                                <ul>
                                                {% for gl in object.gite_localisation.all %}
                                                    <li> {{ gl.descr }}</li>
                                                {% endfor %}
                                                </ul>
                                            {% else %}
                                                Aucune localisation indiquée
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="accordion-item" data-accordion-item>
                    <a class="accordion-title">Localité</a>
                    <div class="accordion-content" data-tab-content>
                        <div class="row">
                            <div class="large-12 columns">
                                <div class="medium-6 small-12 columns">
                                    <label>Nom</label>
                                    <div class="small callout">
                                        <a href="{% url 'sights:place_detail' pk=object.place.id_place %}">{{ object.place.id_place }}
                                            / {{ object.place }}</a></div>
                                </div>
                                <div class="medium-6 small-12 columns">
                                    <label>Situation</label>
                                    <div class="small callout">{{ object.place.municipality.name }}
                                        ({{ object.place.territory.code }})
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                {% if object.comment %}
                    <li class="accordion-item" data-accordion-item>
                        <a class="accordion-title">Commentaire</a>
                        <div class="accordion-content" data-tab-content>
                            <div class="row">
                                <div class="large-12 columns">
                                    {{ object.comment|safe }}
                                </div>
                            </div>
                        </div>
                    </li>
                {% endif %}
            </div>
            <br/>
            <div class="button-group radius">
                <a title="Retour à la session" class="button"
                   href="{% url 'sights:place_detail' pk=object.place.id_place %}"><i class="fi-arrow-left"></i>
                    Retour</a>
                <a title="Modifier cette observation" class="button warning"
                   href="{% url 'sights:tree_update' pk=object.id_tree %}"><i class="fa fa-fw fa-pencil-square-o"></i>
                    Modifier</a>
                <a title="Supprimer cette localité" class="button alert"
                   href="{% url 'sights:tree_delete' pk=object.id_tree %}"><i class="fa fa-fw fa-trash"></i>
                    Supprimer</a>
            </div>
        </div>

        <div class="large-6 medium-12 columns">
            <h3>
                <si class="{{ treegiteicon | safe }}"></i> {{ treegitetitle | safe }}
            </h3>
            {% if treegitecount > 0 %}
                <div class="input-group">
                    <span class="input-group-label"><i class="fi-info"></i></span>
                    {% ifequal 1 treegitecount %}
                        <input class="input-group-field" type="text"
                               value="{{ treegitecount }} donnée détaillée"
                               readonly>
                    {% else %}
                        <input class="input-group-field" type="text"
                               value="{{ treegitecount }} données détaillées"
                               readonly>
                    {% endifequal %}
                    <div class="input-group-button">
                        <a href="{% url 'sights:treegite_create' pk=object.pk %}" class="button"
                           title="Créer un nouveau relevé détaillé"><i class="fi-plus"></i></a>
                    </div>
                </div>
                {% if treegitecount > 0 %}

                    {% render_table treegitetable %}

                {% endif %}
            {% else %}
                <div class="input-group">
                    <span class="input-group-label"><i class="fi-info"></i></span>
                    <input class="input-group-field" type="text" value="Aucune observation" readonly>
                    <div class="input-group-button">
                        <a href="{% url 'sights:treegite_create' pk=object.pk %}" class="button"
                           title="Créer un nouveau relevé détaillé"><i class="fi-plus"></i></a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    <br/> {% endblock %}